image: 
- Visual Studio 2017
install:
- pip install --user upgrade pip==19.0.3
test_script:
- python src/fileio.py
- python src/fs_tools.py
#- python src/gui.py
- python src/neuralnet.py
- python src/simulation.py
- python src/summersim.py
build: off
