image: 
- Visual Studio 2017
 matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64
test_script:
- python src/fileio.py
- python src/fs_tools.py
- python src/gui.py
- python src/neuralnet.py
- python src/simulation.py
- python src/summersim.py
build: off
